/// @file generated_progression_registry.hpp
/// @brief Auto-generated progression registry entries.
/// @warning DO NOT EDIT - generated by generate_progression_registry.py
///
/// Source directory scanned: /mnt/c/Users/aksha/Desktop/hackerman/projects/basketballgm/progbox_cpp
/// Registered strategies: 3

#pragma once

// ============================================================================
// REQUIRED INCLUDES
// ============================================================================

#include "i_progression.hpp"

// ============================================================================
// PROGRESSION IMPLEMENTATION INCLUDES
// ============================================================================
#include "v0_progression.hpp"
#include "v321_progression.hpp"
#include "v41_progression.hpp"

// ============================================================================
// GENERATED REGISTRY ENTRIES
// ============================================================================

namespace progbox {
namespace generated {

/// @brief Get auto-generated progression registry entries.
inline const std::vector<ProgressionEntry>& entries() {
    static const std::vector<ProgressionEntry> registry = {
        {
            "v0",
            "Baseline (BBGM developSeason port)",
            []() -> std::unique_ptr<IProgressionStrategy> { return std::make_unique<V0Progression>(); }
        },
        {
            "v321",
            "v3.2.1, current progression script",
            []() -> std::unique_ptr<IProgressionStrategy> { return std::make_unique<V321Progression>(); }
        },
        {
            "v41",
            "v4.1, new progression script with EWA and DWS on top of PER",
            []() -> std::unique_ptr<IProgressionStrategy> { return std::make_unique<V41Progression>(); }
        },
    };
    return registry;
}

} // namespace generated
} // namespace progbox
